// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMozNwSy-RRjEoq1XQWJgddA3E-Csqqs',
    appId: '1:371570013381:web:07c87abc079746d2ac2cac',
    messagingSenderId: '371570013381',
    projectId: 'legal-lens-475215',
    authDomain: 'legal-lens-475215.firebaseapp.com',
    storageBucket: 'legal-lens-475215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5yLt-3TfCbrWbObwnLffP4zGuuWZk-0',
    appId: '1:371570013381:android:20738c3fe35d8953ac2cac',
    messagingSenderId: '371570013381',
    projectId: 'legal-lens-475215',
    storageBucket: 'legal-lens-475215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6f2dPEg3PvoEAuXP8H1xL0Ku4BMsAdY',
    appId: '1:371570013381:ios:5fbce700fb76f9e9ac2cac',
    messagingSenderId: '371570013381',
    projectId: 'legal-lens-475215',
    storageBucket: 'legal-lens-475215.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE6f2dPEg3PvoEAuXP8H1xL0Ku4BMsAdY',
    appId: '1:371570013381:ios:b540214f6b85ddceac2cac',
    messagingSenderId: '371570013381',
    projectId: 'legal-lens-475215',
    storageBucket: 'legal-lens-475215.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATMozNwSy-RRjEoq1XQWJgddA3E-Csqqs',
    appId: '1:371570013381:web:b3e96a57b016fb9aac2cac',
    messagingSenderId: '371570013381',
    projectId: 'legal-lens-475215',
    authDomain: 'legal-lens-475215.firebaseapp.com',
    storageBucket: 'legal-lens-475215.firebasestorage.app',
  );

}