// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your_api',
    appId: '1:795183661271:web:704848dc37503b0b78f092',
    messagingSenderId: '795183661271',
    projectId: 'legallens-b5f95',
    authDomain: 'legallens-b5f95.firebaseapp.com',
    storageBucket: 'legallens-b5f95.firebasestorage.app',
    measurementId: 'G-GD3E9Y8Y0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_api',
    appId: '1:795183661271:android:32cd70578547479878f092',
    messagingSenderId: '795183661271',
    projectId: 'legallens-b5f95',
    storageBucket: 'legallens-b5f95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_api',
    appId: '1:795183661271:ios:ee165764f68332b678f092',
    messagingSenderId: '795183661271',
    projectId: 'legallens-b5f95',
    storageBucket: 'legallens-b5f95.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_api',
    appId: '1:795183661271:ios:ee165764f68332b678f092',
    messagingSenderId: '795183661271',
    projectId: 'legallens-b5f95',
    storageBucket: 'legallens-b5f95.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_api',
    appId: '1:795183661271:web:9a3e952cfd92292978f092',
    messagingSenderId: '795183661271',
    projectId: 'legallens-b5f95',
    authDomain: 'legallens-b5f95.firebaseapp.com',
    storageBucket: 'legallens-b5f95.firebasestorage.app',
    measurementId: 'G-MCEZRX0VJ8',
  );

}